// Dependency-free perspective campus. Geometry is projected from a walkable camera.
export function campusSceneHTML(rooms){return `<section class="campus-walk"><div class="campus-walk-toolbar"><div><strong>アニメの校舎を歩く</strong><small>ドラッグで見回す · 移動ボタン / WASD・矢印キー · 部屋札をクリックして入室</small></div><div><button data-campus-view="yard">校庭</button><button data-campus-view="hall">廊下に入る</button><button data-campus-full>⛶ 大きく表示</button></div></div><div class="campus-scene"><canvas id="campus-scene" tabindex="0" aria-label="学校構内の3D案内。WASDで移動、ドラッグで視線を回転。下の教室一覧からも入室できます。"></canvas><div class="campus-location" id="campus-location">校庭 · 正面玄関</div><div class="campus-crosshair" aria-hidden="true">＋</div><div class="campus-motion" aria-label="構内の移動"><button data-campus-move="forward" aria-label="前へ進む">↑</button><div><button data-campus-move="left" aria-label="左へ移動">←</button><button data-campus-move="back" aria-label="後ろへ移動">↓</button><button data-campus-move="right" aria-label="右へ移動">→</button></div></div><p id="campus-scene-hint" role="status">玄関をクリックすると廊下へ入れます</p></div><nav class="school3d-room-links" aria-label="教室一覧">${rooms.map(r=>`<button data-room="${r[0]}">${r[4]} ${r[2]}</button>`).join('')}</nav></section>`;}
export function bindCampusScene({rooms,onEnter}){
 const canvas=document.querySelector('#campus-scene');if(!canvas)return ()=>{};const ctx=canvas.getContext('2d');if(!ctx)return ()=>{};
 const root=canvas.closest('.campus-walk'),hint=root.querySelector('#campus-scene-hint'),locationLabel=root.querySelector('#campus-location');
 let width=1,height=1,view='yard',eye=[0,1.7,13],yaw=0,pitch=0,faces=[],signs=[],hits=[],hover=null,drag=null,frame=0,last=0,dirty=true,disposed=false;
 const moving=new Set();
 const hallAtlas=new Image();hallAtlas.src=new URL('./assets/summer-school-atlas.webp',import.meta.url).href;hallAtlas.onload=()=>{dirty=true;};
 const yardAtlas=new Image();yardAtlas.src=new URL('./assets/summer-yard-atlas.webp',import.meta.url).href;yardAtlas.onload=()=>{dirty=true;};
 const skyArt=new Image();skyArt.src=new URL('./assets/summer-sky.webp',import.meta.url).href;skyArt.onload=()=>{dirty=true;};
 const facadeArt=new Image();facadeArt.src=new URL('./assets/summer-facade-lawn.webp',import.meta.url).href;facadeArt.onload=()=>{dirty=true;};
 const natureArts=[new Image(),new Image()],natureCrops=[],natureRender=[];natureArts.forEach((art,panel)=>{art.onload=()=>{const sheet=document.createElement('canvas');sheet.width=art.width;sheet.height=art.height;const brush=sheet.getContext('2d');brush.drawImage(art,0,0);const imageData=brush.getImageData(0,0,sheet.width,sheet.height),pixels=imageData.data;for(let i=3;i<pixels.length;i+=4)pixels[i]=pixels[i]<150?0:Math.min(255,(pixels[i]-150)*3);brush.putImageData(imageData,0,0);natureRender[panel]=sheet;let left=sheet.width,right=0,top=sheet.height,bottom=0;for(let y=0;y<sheet.height;y++)for(let x=0;x<sheet.width;x++)if(pixels[(y*sheet.width+x)*4+3]>24){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}natureCrops[panel]=[left,top,right-left+1,bottom-top+1];dirty=true;};art.src=new URL(panel?'./assets/summer-bench.webp':'./assets/summer-tree.webp',import.meta.url).href;});
 const sprite=(x,z,w,h,panel)=>faces.push({vertices:[],color:'#ffffff00',outline:false,sprite:{x,z,w,h,panel}});
 function spriteVertices(s){const angle=Math.atan2(eye[0]-s.x,eye[2]-s.z),dx=Math.cos(angle)*s.w/2,dz=-Math.sin(angle)*s.w/2;return [[s.x-dx,0,s.z-dz],[s.x+dx,0,s.z+dz],[s.x+dx,s.h,s.z+dz],[s.x-dx,s.h,s.z-dz]];}
 const yardCells={'#ba8e60':[0,0],'#beddd6':[1,0],'#a8ce7a':[2,0],'#bd7968':[0,1],'#995d53':[0,1],'#d8c79e':[1,1]};
 const textureCells={'#bd946a':[0,0],'#f5efde':[1,0],'#dce4e9':[0,1],'#a5d9ef':[1,1]};
 function paintTexture(face){const spriteCrop=face.sprite&&natureCrops[face.sprite.panel];if(face.sprite&&!spriteCrop)return;const wideMaterial=view==='yard'&&['#ba8e60','#a8ce7a'].includes(face.color);const atlas=face.sprite?natureRender[face.sprite.panel]:wideMaterial?facadeArt:view==='yard'?yardAtlas:hallAtlas;if((!face.sprite&&(!atlas.complete||!atlas.naturalWidth))||face.vertices.length!==4)return;let cell=view==='yard'?(face.textureCell||yardCells[face.color]):textureCells[face.color];if(['#c9a574','#d8b887','#be996d','#dcc198'].includes(face.color))cell=[2,0];if(wideMaterial)cell=[0,face.color==='#a8ce7a'?1:0];if(face.sprite)cell=[0,0];if(!cell)return;const [a,b,c,d]=face.vertices,steps=face.center?1:face.id?6:3,tw=atlas.width/(wideMaterial?1:3),th=atlas.height/2;const at=(u,v)=>project(a.map((x,i)=>x*(1-u)*(1-v)+b[i]*u*(1-v)+c[i]*u*v+d[i]*(1-u)*v));const uv=(u,v)=>{if(spriteCrop)return [spriteCrop[0]+u*spriteCrop[2],spriteCrop[1]+(1-v)*spriteCrop[3]];if(wideMaterial&&face.color==='#a8ce7a'){const q=a.map((x,i)=>x*(1-u)*(1-v)+b[i]*u*(1-v)+c[i]*u*v+d[i]*(1-u)*v);return [(q[0]+28)/56*tw,(1+(q[2]+28)/60)*th];}if(face.center){const q=a.map((x,i)=>x*(1-u)*(1-v)+b[i]*u*(1-v)+c[i]*u*v+d[i]*(1-u)*v);return [(cell[0]+Math.max(0,Math.min(1,.5+(q[0]-face.center[0])/(2*face.radius))))*tw,(cell[1]+Math.max(0,Math.min(1,.5-(q[1]-face.center[1])/(2*face.radius))))*th];}return [(cell[0]+u)*tw,(cell[1]+1-v)*th];};for(let y=0;y<steps;y++)for(let x=0;x<steps;x++){const u=x/steps,v=y/steps,U=(x+1)/steps,V=(y+1)/steps,points=[at(u,v),at(U,v),at(U,V),at(u,V)],src=[uv(u,v),uv(U,v),uv(U,V),uv(u,V)];if(points.some(p=>!p))continue;for(const indices of [[0,1,2],[0,2,3]]){const [p0,p1,p2]=indices.map(i=>points[i]),[t0,t1,t2]=indices.map(i=>src[i]);const dx1=t1[0]-t0[0],dy1=t1[1]-t0[1],dx2=t2[0]-t0[0],dy2=t2[1]-t0[1],det=dx1*dy2-dx2*dy1;if(!det)continue;const A=((p1.x-p0.x)*dy2-(p2.x-p0.x)*dy1)/det,B=((p1.y-p0.y)*dy2-(p2.y-p0.y)*dy1)/det,C=((p2.x-p0.x)*dx1-(p1.x-p0.x)*dx2)/det,D=((p2.y-p0.y)*dx1-(p1.y-p0.y)*dx2)/det;ctx.save();ctx.beginPath();ctx.moveTo(p0.x,p0.y);ctx.lineTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);ctx.closePath();ctx.clip();ctx.transform(A,B,C,D,p0.x-A*t0[0]-C*t0[1],p0.y-B*t0[0]-D*t0[1]);if(spriteCrop)ctx.drawImage(atlas,...spriteCrop,...spriteCrop);else ctx.drawImage(atlas,cell[0]*tw,cell[1]*th,tw,th,cell[0]*tw,cell[1]*th,tw,th);ctx.restore();}}}

 const polygon=(vertices,color,id=null,outline=true)=>faces.push({vertices,color,id,outline});
 const box=(x,y,z,w,h,d,color,id=null)=>{const a=x-w/2,b=x+w/2,c=y,e=y+h,f=z-d/2,g=z+d/2,outline=w>.25&&h>.25;polygon([[a,c,g],[b,c,g],[b,e,g],[a,e,g]],color,id,outline);polygon([[b,c,f],[a,c,f],[a,e,f],[b,e,f]],color,id,outline);polygon([[a,c,f],[a,c,g],[a,e,g],[a,e,f]],shade(color,.74),id,outline);polygon([[b,c,g],[b,c,f],[b,e,f],[b,e,g]],shade(color,.85),id,outline);polygon([[a,e,g],[b,e,g],[b,e,f],[a,e,f]],shade(color,1.16),id,outline);};
 function shade(color,amount){amount=amount<.9?.83:amount>1.08?1.12:1;const n=parseInt(color.slice(1),16);return '#'+[n>>16,n>>8&255,n&255].map((v,i)=>Math.min(255,Math.round(v*amount+(amount<1?[0,5,11][i]:0))).toString(16).padStart(2,'0')).join('');}
 const sign=(x,y,z,text,id)=>signs.push({point:[x,y,z],text,id});
 const sphere=(x,y,z,r,color,scale=[1,1,1])=>{const rows=8,columns=16;for(let row=0;row<rows;row++)for(let col=0;col<columns;col++){const point=(a,b)=>[x+r*scale[0]*Math.sin(a)*Math.cos(b),y+r*scale[1]*Math.cos(a),z+r*scale[2]*Math.sin(a)*Math.sin(b)];const a=row*Math.PI/rows,b=col*2*Math.PI/columns,cloud=color==='#ffffff'||color==='#f6fbff';polygon([point(a,b),point(a+Math.PI/rows,b),point(a+Math.PI/rows,b+2*Math.PI/columns),point(a,b+2*Math.PI/columns)],cloud?(row>5?'#e5f1f7':color):shade(color,.85+.22*Math.cos(b)),null,false);faces[faces.length-1].center=[x,y,z];faces[faces.length-1].radius=r;if(!cloud)faces[faces.length-1].textureCell=[2,1];}};
 const tree=(x,z,size=1)=>sprite(x,z,4.8*size,6.2*size,0);
 const floor=(color,bounds)=>{for(let x=bounds[0];x<bounds[1];x+=2)for(let z=bounds[2];z<bounds[3];z+=2)polygon([[x,0,z],[x+2.01,0,z],[x+2.01,0,z+2.01],[x,0,z+2.01]],view==='yard'&&x>=-2&&x<2&&z>=-8?'#d8c79e':(x+z)%4?shade(color,.98):color,null,false);};
 function geometry(){faces=[];signs=[];
 if(view==='yard'){
 floor('#a8ce7a',[-28,28,-28,32]);
 box(0,0,-12,28,6.2,6,'#ba8e60');box(0,0,-8.95,28,.55,.15,'#989487');

  const roof='#bd7968';polygon([[-14.7,6.2,-8.4],[14.7,6.2,-8.4],[14.7,8.3,-12],[-14.7,8.3,-12]],roof);polygon([[-14.7,8.3,-12],[14.7,8.3,-12],[14.7,6.2,-15.6],[-14.7,6.2,-15.6]],'#995d53');polygon([[-14.7,6.2,-15.6],[-14.7,6.2,-8.4],[-14.7,8.3,-12]],'#bd9768');polygon([[14.7,6.2,-8.4],[14.7,6.2,-15.6],[14.7,8.3,-12]],'#bd9768');

 polygon([[-1.3,.1,-8.8],[1.3,.1,-8.8],[1.3,2.6,-8.8],[-1.3,2.6,-8.8]],'#00000008','entrance',false);box(-1.8,0,-7.8,.25,3.2,.25,'#a7987c');box(1.8,0,-7.8,.25,3.2,.25,'#a7987c');box(0,3,-7.9,4,.3,2.5,'#80634a');box(0,0,-7.1,4,.25,2.7,'#a7a18b');sign(0,3.6,-8.5,'デジタルエンジニア学校','entrance');
 [[-19,3],[-20,-9],[19,-5],[22,10],[-13,15]].forEach(([x,z],i)=>{tree(x,z,.9+i*.09);polygon([[x-2,.025,z-1],[x+2,.025,z-1],[x+5,.025,z+4],[x+1,.025,z+5]],'#426c8750',null,false);});
 for(const x of [-7,7])sprite(x,3,3.4,1.5,1);
 box(-6,0,-5,.25,1.7,.25,'#6c5740');box(-6,1.3,-5,2.5,.9,.18,'#f2e5c5');sign(-6,1.8,-4.85,'共同開発棟 →',null);
 }else{

 // Narrow timber boards, with deterministic grain and blue ambient shadows.
 for(let x=-16;x<16;x+=.48)for(let z=-9;z<12;z+=2.4){const tone=['#c9a574','#d8b887','#be996d','#dcc198'][Math.abs(Math.round(x*10+z*5))%4];polygon([[x,.012,z],[x+.465,.012,z],[x+.465,.012,z+2.38],[x,.012,z+2.38]],tone,null,true);for(let g=0;g<2;g++)polygon([[x+.12+g*.16,.014,z+.15],[x+.127+g*.16,.014,z+.15],[x+.127+g*.16,.014,z+2.15],[x+.12+g*.16,.014,z+2.15]],'#b7987280',null,false);}
box(0,0,-5,30,3.5,.3,'#f5efde');for(let z=-5;z<9;z+=.5){box(-15,0,z+.25,.3,3.5,.5,'#e4e8e5');box(15,0,z+.25,.3,3.5,.5,'#e4e8e5');}box(0,0,-4.78,30,.65,.12,'#ad8861');
 for(let x=-15;x<16;x+=.6)box(x,0,-4.69,.035,.65,.08,'#d3b38b');
 rooms.forEach((r,i)=>{const x=(i-(rooms.length-1)/2)*Math.min(4.6,26/Math.max(1,rooms.length-1));box(x,.1,-4.65,2.8,2.8,.2,'#bd946a',r[0]);box(x-1.48,.05,-4.49,.13,2.95,.16,'#967956');box(x+1.48,.05,-4.49,.13,2.95,.16,'#967956');box(x,2.94,-4.49,3.08,.14,.16,'#dfc59d');for(let g=-1.2;g<1.3;g+=.18)box(x+g,.2,-4.535,.012,1.12,.013,'#a77f5544');box(x,3,-4.4,3.5,.4,.12,'#3b4736',r[0]);sign(x,3.2,-4.25,r[2],r[0]);});
 for(let z=-2;z<10;z+=3){box(14.78,.85,z,.1,2.25,2.2,'#a5d9ef');for(const offset of [-1.1,0,1.1])box(14.6,.85,z+offset,.17,2.25,.055,'#f5f4e9');box(14.6,1.95,z,.17,.06,2.2,'#f5f4e9');box(14.56,.8,z,.35,.09,2.35,'#efe5d1');box(14.65,1,z,.16,2,.055,'#87775a');box(-14.8,1,z,.1,1.5,1.8,'#e7d4a2');}
 box(0,3.5,1,30,.1,14,'#dce4e9');polygon([[-15,3.5,-6],[15,3.5,-6],[15,3.5,8],[-15,3.5,8]],'#dce4e9',null,false);for(let x=-10;x<=10;x+=5)box(x,3.35,0,1,.09,.35,'#fff2ca');
 box(-13,.45,5,2,.15,.75,'#9d7850');box(-13,1,5.4,2,.7,.1,'#9d7850');sign(0,1.35,8,'← 校庭へ戻る','yard');

 // Afternoon window light across the floor and classroom wall.
 for(let z=-2;z<10;z+=3){polygon([[14.4,.027,z-1],[14.4,.027,z+1],[2,.027,z-2],[2,.027,z-4]],'#fff1ba65',null,false);polygon([[14.4,.029,z-.06],[14.4,.029,z+.06],[2,.029,z-2.94],[2,.029,z-3.06]],'#7893a544',null,false);}
 for(let x=-14;x<14;x+=4.6){polygon([[x,.72,-4.35],[x+2.7,.72,-4.35],[x+1.3,2.85,-4.35],[x-.6,2.85,-4.35]],'#fff3bf40',null,false);}
 }
 }
 function setView(next){view=next;eye=next==='hall'?[0,1.65,3.5]:[0,1.7,13];yaw=0;pitch=0;moving.clear();hover=null;geometry();dirty=true;locationLabel.textContent=next==='hall'?'共同開発棟 · 木の廊下':'校庭 · 正面玄関';hint.textContent=next==='hall'?'部屋札または扉をクリックして入室':'玄関をクリックして廊下へ';root.querySelectorAll('[data-campus-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.campusView===next)));}
 function project(point){const x=point[0]-eye[0],y=point[1]-eye[1],z=eye[2]-point[2];const a=x*Math.cos(yaw)-z*Math.sin(yaw),b=x*Math.sin(yaw)+z*Math.cos(yaw),vertical=y*Math.cos(pitch)-b*Math.sin(pitch),depth=y*Math.sin(pitch)+b*Math.cos(pitch);if(depth<.15)return null;const focal=Math.min(width,height)*.94;return {x:width/2+a*focal/depth,y:height*.5-vertical*focal/depth,z:depth};}
 function draw(){const sky=ctx.createLinearGradient(0,0,0,height);sky.addColorStop(0,view==='yard'?'#298cdb':'#cbdce9');sky.addColorStop(1,view==='yard'?'#e2f5ff':'#e8d9bd');ctx.fillStyle=sky;ctx.fillRect(0,0,width,height);if(view==='yard'&&skyArt.complete&&skyArt.naturalWidth){const scale=Math.max(width/skyArt.width,height/skyArt.height),w=skyArt.width*scale,h=skyArt.height*scale;ctx.drawImage(skyArt,(width-w)/2-Math.sin(yaw)*width*.12,(height-h)/2+pitch*height*.3,w,h);}hits=[];
 const visible=[];for(const face of faces){if(face.sprite)face.vertices=spriteVertices(face.sprite);if(face.center){const mid=face.vertices.reduce((a,p)=>a.map((v,i)=>v+p[i]/face.vertices.length),[0,0,0]);if(mid.reduce((sum,v,i)=>sum+(v-face.center[i])*(eye[i]-v),0)<=0)continue;}const points=face.vertices.map(project);if(points.some(p=>!p))continue;visible.push({...face,points,depth:points.reduce((v,p)=>v+p.z,0)/points.length});}visible.sort((a,b)=>b.depth-a.depth);
 for(const face of visible){const p=face.points;ctx.beginPath();ctx.moveTo(p[0].x,p[0].y);p.slice(1).forEach(v=>ctx.lineTo(v.x,v.y));ctx.closePath();ctx.fillStyle=face.id&&face.id===hover?'#cbaa5e':face.color;ctx.fill();ctx.save();if(view==='yard'&&(face.center||face.color==='#a8ce7a'))ctx.globalAlpha=face.center?.85:1;paintTexture(face);ctx.restore();if(face.id&&face.id===hover){ctx.fillStyle='#ffe59855';ctx.fill();}if(face.outline){ctx.strokeStyle=face.id&&face.id===hover?'#ffe598':'#66503b88';ctx.lineWidth=face.id?1.4:.65;ctx.lineJoin='round';ctx.stroke();}if(face.id||face.color.length===7)hits.push({points:p,id:face.id,depth:face.depth});}
 const glow=ctx.createLinearGradient(width,0,0,height);glow.addColorStop(0,'#fff5d323');glow.addColorStop(.65,'#ffffff00');glow.addColorStop(1,'#5689b015');ctx.fillStyle=glow;ctx.fillRect(0,0,width,height);
 for(const label of signs){const p=project(label.point);if(!p)continue;const cover=[...hits].reverse().find(hit=>inside(p,hit.points));if(cover&&cover.depth<p.z-.4&&cover.id!==label.id)continue;const size=Math.max(10,Math.min(25,120/p.z));ctx.font=`600 ${size}px system-ui`;const w=ctx.measureText(label.text).width+20;ctx.fillStyle=label.id===hover?'#b18a39':'#394334';ctx.fillRect(p.x-w/2,p.y-size,w,size+12);ctx.strokeStyle='#5a4b3e';ctx.lineWidth=1.5;ctx.strokeRect(p.x-w/2,p.y-size,w,size+12);ctx.fillStyle='#fff1d4';ctx.textAlign='center';ctx.fillText(label.text,p.x,p.y+2);if(label.id)hits.push({id:label.id,points:[{x:p.x-w/2,y:p.y-size},{x:p.x+w/2,y:p.y-size},{x:p.x+w/2,y:p.y+12},{x:p.x-w/2,y:p.y+12}]});}
 }
 function inside(point,polygon){let result=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if(((a.y>point.y)!==(b.y>point.y))&&(point.x<(b.x-a.x)*(point.y-a.y)/(b.y-a.y)+a.x))result=!result;}return result;}
 const pick=e=>{const rect=canvas.getBoundingClientRect(),point={x:e.clientX-rect.left,y:e.clientY-rect.top};return [...hits].reverse().find(hit=>inside(point,hit.points))?.id||null;};
 function move(dt){let f=(moving.has('forward')?1:0)-(moving.has('back')?1:0),side=(moving.has('right')?1:0)-(moving.has('left')?1:0);if(!f&&!side)return;const speed=dt*4/Math.max(1,Math.hypot(f,side));eye[0]+= (Math.sin(yaw)*f+Math.cos(yaw)*side)*speed;eye[2]+= (-Math.cos(yaw)*f+Math.sin(yaw)*side)*speed;eye[0]=Math.max(view==='hall'?-13:-25,Math.min(view==='hall'?13:25,eye[0]));eye[2]=Math.max(view==='hall'?-2.5:-5.5,Math.min(view==='hall'?10:28,eye[2]));dirty=true;}
 function tick(time){if(disposed||!canvas.isConnected){dispose();return;}move(Math.min(.05,(time-last)/1000||0));last=time;if(dirty){draw();dirty=false;}frame=requestAnimationFrame(tick);}
 const resize=()=>{const rect=canvas.getBoundingClientRect();width=Math.max(1,rect.width);height=Math.max(1,rect.height);const dpr=Math.min(2,devicePixelRatio||1);canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);dirty=true;};const observer=new ResizeObserver(resize);observer.observe(canvas);
 canvas.onpointerdown=e=>{if(e.button!==0)return;canvas.focus({preventScroll:true});drag={id:e.pointerId,x:e.clientX,y:e.clientY,yaw,pitch,moved:false};canvas.setPointerCapture(e.pointerId);};
 canvas.onpointermove=e=>{if(drag&&e.pointerId===drag.id){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>5)drag.moved=true;yaw=drag.yaw-dx*.005;pitch=Math.max(-.5,Math.min(.5,drag.pitch+dy*.004));dirty=true;}else{const next=pick(e);if(next!==hover){hover=next;dirty=true;canvas.style.cursor=hover?'pointer':'grab';hint.textContent=hover==='entrance'?'玄関から廊下へ入る':hover==='yard'?'校庭へ戻る':rooms.find(r=>r[0]===hover)?.[2]+' · クリックして入室';if(!hover)hint.textContent=view==='hall'?'部屋札・扉をクリックして入室':'玄関をクリックして廊下へ';}}};
 canvas.onpointerup=e=>{if(!drag)return;const clicked=!drag.moved;drag=null;if(clicked){const id=pick(e);if(id==='entrance')setView('hall');else if(id==='yard')setView('yard');else if(id)onEnter(id);}};canvas.onpointercancel=()=>{drag=null;};
 const keys={w:'forward',ArrowUp:'forward',s:'back',ArrowDown:'back',a:'left',ArrowLeft:'left',d:'right',ArrowRight:'right'};
 canvas.onkeydown=e=>{const direction=keys[e.key]||keys[e.key.toLowerCase()];if(direction){e.preventDefault();moving.add(direction);}};canvas.onkeyup=e=>moving.delete(keys[e.key]||keys[e.key.toLowerCase()]);canvas.onblur=()=>moving.clear();
 root.querySelectorAll('[data-campus-move]').forEach(button=>{button.onpointerdown=e=>{e.preventDefault();button.setPointerCapture(e.pointerId);moving.add(button.dataset.campusMove);};button.onpointerup=button.onpointercancel=()=>moving.delete(button.dataset.campusMove);});
 root.querySelectorAll('[data-campus-view]').forEach(button=>button.onclick=()=>setView(button.dataset.campusView));root.querySelector('[data-campus-full]').onclick=()=>{root.classList.toggle('campus-walk-expanded');dirty=true;};
 const escape=e=>{if(e.key==='Escape'){root.classList.remove('campus-walk-expanded');moving.clear();}};document.addEventListener('keydown',escape);
 function dispose(){if(disposed)return;disposed=true;cancelAnimationFrame(frame);observer.disconnect();moving.clear();document.removeEventListener('keydown',escape);}
 setView('yard');resize();frame=requestAnimationFrame(tick);return dispose;
}
