import {state,list,put,remove,canEdit,cursor} from './store.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const parts=[['note','付箋','気づき・アイデア',180,130,'#f5d66a'],['frame','画面フレーム','画面名',350,400,'#ffffff'],['button','ボタン','保存する',140,48,'#346b5e'],['input','入力欄','入力してください',220,50,'#ffffff'],['card','カード','カードの内容',220,150,'#ffffff'],['rect','長方形','処理',180,80,'#cbe2ef'],['circle','円','開始',90,90,'#d6eacb'],['diamond','判断','条件',110,110,'#f4dcae'],['text','テキスト','テキスト',220,60,'#ffffff'],['arrow','矢印','',180,40,'#23483e'],['nav','ナビゲーション','ホーム　一覧　設定',320,55,'#e3e8ef'],['table','表','名前　担当　状態\nサンプル　開発　進行中',300,130,'#ffffff'],['checkbox','チェック欄','□ 同意する',200,48,'#ffffff'],['badge','バッジ','進行中',100,36,'#d6eacb']];
let zoom=1,selected=null,dragging=false;
export function canvasHTML(mode,projectId){const objects=list(mode,projectId);return `<div class="canvas-tools"><div class="part-list">${parts.filter(p=>mode!=='refine'||['note','text','rect','circle','diamond','arrow'].includes(p[0])).map(p=>`<button data-part="${p[0]}" ${canEdit()?'':'disabled'}>${p[1]}</button>`).join('')}</div><div class="row"><button data-zoom="out" aria-label="縮小">−</button><span id="zoom-label">${Math.round(zoom*100)}%</span><button data-zoom="in" aria-label="拡大">＋</button><button data-action="exportCanvas">JSON保存</button></div></div><div class="canvas-layout"><div class="canvas-viewport" id="canvas-viewport"><div id="canvas-world" style="transform:scale(${zoom})" tabindex="0" aria-label="共同編集キャンバス">${objects.map(objectHTML).join('')}<div id="cursors"></div></div></div><aside class="canvas-properties"><div class="section-label">部品の設定</div><div id="object-properties">部品を選ぶと内容・位置・サイズを編集できます。<p class="muted">ドラッグで移動。矢印キーで位置調整。Deleteで削除。</p></div></aside></div>`}
function objectHTML(e){const p=e.payload;return `<div class="canvas-object shape-${esc(p.type)} ${e.id===selected?'selected':''}" tabindex="0" role="button" aria-label="${esc(p.text||p.type)}" data-object="${e.id}" style="left:${Number(p.x)||0}px;top:${Number(p.y)||0}px;width:${Number(p.w)||180}px;height:${Number(p.h)||100}px;--object-color:${/^#[0-9a-f]{6}$/i.test(p.color)?p.color:'#ffffff'}"><span>${esc(p.text)}</span></div>`}
export function bindCanvas({projectId,mode,notify,dialog,download}){
 const world=document.querySelector('#canvas-world');if(!world)return;const viewport=document.querySelector('#canvas-viewport');
 const refresh=()=>{if(dragging)return;world.querySelectorAll('[data-object]').forEach(n=>n.remove());world.insertAdjacentHTML('afterbegin',list(mode,projectId).map(objectHTML).join(''));if(selected&&!document.activeElement?.closest('#object-properties'))properties()};
 const properties=()=>{const e=state.entities.find(e=>e.id===selected);const target=document.querySelector('#object-properties');if(!e){target.textContent='部品を選択してください。';return}const p=e.payload;target.innerHTML=`<form id="property-form"><label>内容<textarea name="text">${esc(p.text)}</textarea></label><div class="two-col">${[['x','X'],['y','Y'],['w','幅'],['h','高さ']].map(([key,label])=>`<label>${label}<input type="number" name="${key}" value="${Number(p[key])}" min="${['w','h'].includes(key)?24:0}" max="${['w','h'].includes(key)?1200:2200}"></label>`).join('')}</div><label>色<input type="color" name="color" value="${esc(p.color)}"></label><button class="primary" ${canEdit()?'':'disabled'}>変更を保存</button></form><div class="row"><button data-duplicate ${canEdit()?'':'disabled'}>複製</button><button class="danger" data-remove ${canEdit()?'':'disabled'}>削除</button></div>`;
 target.querySelector('form').onsubmit=async event=>{event.preventDefault();const f=new FormData(event.target);try{await put(projectId,mode,{...p,text:f.get('text'),color:f.get('color'),...Object.fromEntries(['x','y','w','h'].map(k=>[k,Math.min(['w','h'].includes(k)?1200:2200,Math.max(['w','h'].includes(k)?24:0,Number(f.get(k))))]))},e.id,e.version);refresh()}catch(err){notify(err.message)}};
 target.querySelector('[data-duplicate]').onclick=async()=>{try{await put(projectId,mode,{...p,x:Math.min(2200,p.x+24),y:Math.min(2200,p.y+24)});refresh()}catch(err){notify(err.message)}};
 target.querySelector('[data-remove]').onclick=()=>dialog('部品を削除',`<p>「${esc(p.text||p.type)}」を削除します。</p>`,async()=>{await remove(e);selected=null;refresh()},'削除');
 };
 document.querySelectorAll('[data-part]').forEach(b=>b.onclick=async()=>{const part=parts.find(p=>p[0]===b.dataset.part);const count=list(mode,projectId).length;try{const e=await put(projectId,mode,{type:part[0],text:part[2],w:part[3],h:part[4],color:part[5],x:80+count%5*30,y:70+count%5*30});selected=e.id;refresh()}catch(e){notify(e.message)}});
 document.querySelectorAll('[data-zoom]').forEach(b=>b.onclick=()=>{zoom=Math.max(.4,Math.min(1.6,zoom+(b.dataset.zoom==='in'?.1:-.1)));world.style.transform=`scale(${zoom})`;document.querySelector('#zoom-label').textContent=`${Math.round(zoom*100)}%`});
 let drag,lastCursor=0;
 world.onpointerdown=event=>{const node=event.target.closest('[data-object]');if(!node)return;selected=node.dataset.object;world.querySelectorAll('.selected').forEach(n=>n.classList.remove('selected'));node.classList.add('selected');properties();if(!canEdit())return;const e=state.entities.find(e=>e.id===selected);drag={node,e,startX:event.clientX,startY:event.clientY,x:e.payload.x,y:e.payload.y};dragging=true;world.setPointerCapture(event.pointerId);};
 world.onpointermove=event=>{const rect=world.getBoundingClientRect();const now=performance.now();if(now-lastCursor>100){cursor({x:(event.clientX-rect.left)/zoom,y:(event.clientY-rect.top)/zoom,mode});lastCursor=now}if(!drag)return;drag.x=Math.max(0,Math.min(2200,drag.e.payload.x+(event.clientX-drag.startX)/zoom));drag.y=Math.max(0,Math.min(2200,drag.e.payload.y+(event.clientY-drag.startY)/zoom));drag.node.style.left=`${drag.x}px`;drag.node.style.top=`${drag.y}px`;};
 const finish=async()=>{if(!drag)return;const d=drag;drag=null;dragging=false;if(d.x!==d.e.payload.x||d.y!==d.e.payload.y){try{await put(projectId,mode,{...d.e.payload,x:Math.round(d.x),y:Math.round(d.y)},d.e.id,d.e.version)}catch(e){notify(e.message)}}refresh()};world.onpointerup=finish;world.onpointercancel=finish;
 world.onkeydown=async event=>{if(!selected||!canEdit()||event.target.closest('input,textarea'))return;const e=state.entities.find(e=>e.id===selected);if(!e)return;const steps={ArrowLeft:[-10,0],ArrowRight:[10,0],ArrowUp:[0,-10],ArrowDown:[0,10]};try{if(steps[event.key]){event.preventDefault();const [dx,dy]=steps[event.key];await put(projectId,mode,{...e.payload,x:Math.max(0,Math.min(2200,e.payload.x+dx)),y:Math.max(0,Math.min(2200,e.payload.y+dy))},e.id,e.version);refresh()}else if(event.key==='Delete'){event.preventDefault();document.querySelector('[data-remove]')?.click()}}catch(err){notify(err.message)}};
 document.querySelector('[data-action="exportCanvas"]').onclick=()=>download(`${mode}.json`,JSON.stringify(list(mode,projectId).map(e=>e.payload),null,2),'application/json');
 const listener=(event,payload)=>{if(event==='data')refresh();if(event==='cursor'&&payload.userId!==state.user?.id&&payload.mode===mode){const root=document.querySelector('#cursors');if(!root)return;let node=Array.from(root.children).find(n=>n.dataset.user===payload.userId);if(!node){node=document.createElement('div');node.className='peer-cursor';node.dataset.user=payload.userId;root.append(node)}node.style.left=`${Number(payload.x)||0}px`;node.style.top=`${Number(payload.y)||0}px`;node.textContent=`↖ ${payload.name||'参加者'}`;node.dataset.updated=Date.now()}};state.listeners.push(listener);
 const timer=setInterval(()=>{document.querySelectorAll('.peer-cursor').forEach(n=>{if(Date.now()-Number(n.dataset.updated)>6000)n.remove()})},2000);
 return ()=>{clearInterval(timer);state.listeners=state.listeners.filter(fn=>fn!==listener);drag=null;dragging=false};
}
