import {state,id,canEdit} from './store.js';
import {chatTopics,chatMessages,chatProfiles,createChatTopic,postChatMessage} from './community-data.js';
const chatEscape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function communityChatHTML(){return `<section id="community-chat" class="community-chat"><div class="section-heading"><div><h2>テーマを選んで話そう</h2><p class="muted">このプロジェクトの参加者同士で共有する会話です。</p></div><button id="new-chat-topic" class="primary" ${canEdit()?'':'disabled'}>＋ テーマカード</button></div><div class="chat-layout"><aside><div id="chat-topics" class="chat-topic-list"><p class="muted">テーマを読み込み中…</p></div></aside><section class="chat-thread"><div id="chat-thread-heading"><h3>テーマカードを選んでください</h3></div><button id="chat-older" hidden>以前の会話を読む</button><div id="chat-messages" class="chat-messages" role="log" aria-label="テーマの会話履歴"><div class="empty">相談したいテーマを作って、会話をはじめましょう。</div></div><form id="chat-composer" class="chat-composer" hidden><label for="chat-input">メッセージ<textarea id="chat-input" rows="2" maxlength="4000" placeholder="メッセージを入力…" required></textarea></label><div class="row"><small class="muted">Ctrl / Cmd＋Enterで送信</small><button class="primary">送信 ↑</button></div><p id="chat-error" role="alert"></p></form></section></div></section>`;}
export function bindCommunityChat({projectId,topicId,onOpen,notify,dialog}){
 const root=document.querySelector('#community-chat');if(!root)return ()=>{};const topicRoot=root.querySelector('#chat-topics'),messageRoot=root.querySelector('#chat-messages'),composer=root.querySelector('#chat-composer'),input=root.querySelector('#chat-input'),older=root.querySelector('#chat-older');
 let disposed=false,topics=[],current=null,messages=[],profiles=new Map(),more=false,channel=null,loading=false,pendingId=null,pendingText=null;
 const alive=()=>!disposed&&root.isConnected;
 const date=value=>new Date(value).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
 const drawTopics=()=>{topicRoot.innerHTML=topics.map(t=>`<button class="chat-topic-card ${t.id===current?.id?'selected':''}" data-topic="${t.id}"><span>💬 テーマ</span><strong>${chatEscape(t.title)}</strong><p>${chatEscape(t.description)}</p><small>${date(t.created_at)}</small></button>`).join('')||'<div class="empty">テーマはまだありません。編集者がカードを作成できます。</div>';topicRoot.querySelectorAll('[data-topic]').forEach(button=>button.onclick=()=>onOpen(button.dataset.topic));};
 const drawMessages=scroll=>{const oldTop=messageRoot.scrollTop,oldHeight=messageRoot.scrollHeight;messageRoot.innerHTML=messages.map(m=>{const profile=profiles.get(m.author_id),mine=m.author_id===state.user.id;return `<article class="chat-message ${mine?'mine':''}"><div class="chat-message-meta"><span class="avatar chat-avatar" style="background-position:${Number(profile?.avatar||0)%5*25}% ${Math.floor(Number(profile?.avatar||0)/5)*20}%"></span><strong>${chatEscape(profile?.name||'参加者')}</strong><time>${date(m.created_at)}</time></div><p>${chatEscape(m.content)}</p></article>`;}).join('')||'<div class="empty">最初のメッセージを送ってみましょう。</div>';older.hidden=!more;if(scroll==='bottom')messageRoot.scrollTop=messageRoot.scrollHeight;else if(scroll==='prepend')messageRoot.scrollTop=oldTop+(messageRoot.scrollHeight-oldHeight);else messageRoot.scrollTop=oldTop;};
 const fetchProfiles=async rows=>{const unknown=rows.map(m=>m.author_id).filter(uid=>!profiles.has(uid));if(unknown.length){const data=await chatProfiles(unknown);data.forEach(p=>profiles.set(p.id,p));}};
 const append=async message=>{if(!alive()||message.topic_id!==current?.id)return;const nearBottom=messageRoot.scrollHeight-messageRoot.scrollTop-messageRoot.clientHeight<100;await fetchProfiles([message]);if(!alive())return;if(!messages.some(m=>m.id===message.id))messages.push(message);messages.sort((a,b)=>a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id));drawMessages(nearBottom||message.author_id===state.user.id?'bottom':null);};
 async function refreshTopics(){topics=await chatTopics(projectId);if(alive())drawTopics();}
 async function initializeChat(){try{await refreshTopics();if(!alive())return;current=topics.find(t=>t.id===topicId)||null;if(current){drawTopics();root.querySelector('#chat-thread-heading').innerHTML=`<div><h3>${chatEscape(current.title)}</h3><p>${chatEscape(current.description)}</p></div><button id="chat-share-topic">会話URLをコピー</button>`;const data=await chatMessages(current.id);if(!alive())return;messages=data.messages;more=data.more;await fetchProfiles(messages);if(!alive())return;drawMessages('bottom');composer.hidden=false;root.querySelector('#chat-share-topic').onclick=async()=>{const url=location.origin+location.pathname+'#'+new URLSearchParams({p:projectId,r:'communication',item:current.id});try{await navigator.clipboard.writeText(url);notify('会話URLをコピーしました。閲覧はプロジェクト参加者のみです。')}catch{dialog('会話の共有URL',`<label>URL<input readonly value="${chatEscape(url)}"></label>`,async()=>{},'閉じる')}};}else if(topicId)notify('このテーマは見つからないか、参加権限がありません。');
 if(!state.preview){channel=state.client.channel(`room:${projectId}:chat-feed`,{config:{private:true}}).on('postgres_changes',{event:'INSERT',schema:'public',table:'school_chat_topics',filter:`project_id=eq.${projectId}`},()=>refreshTopics().catch(e=>notify(e.message))).on('postgres_changes',{event:'INSERT',schema:'public',table:'school_chat_messages',filter:`project_id=eq.${projectId}`},({new:message})=>append(message).catch(e=>notify(e.message))).subscribe(status=>{if(status==='SUBSCRIBED'&&current)chatMessages(current.id).then(async data=>{for(const message of data.messages)await append(message);}).catch(e=>notify(e.message));else if(['CHANNEL_ERROR','TIMED_OUT'].includes(status))notify('会話の同期を確認してください。「最新の会話」を押して取得できます。');});}
 }catch(error){if(alive())topicRoot.innerHTML=`<p role="alert">${chatEscape(error.message)}</p>`;}}
 root.querySelector('#new-chat-topic').onclick=()=>dialog('会話のテーマカード',`<label>テーマ名<input name="title" maxlength="120" required></label><label>話したいこと<textarea name="description" maxlength="1000" rows="3"></textarea></label>`,async form=>{const topic=await createChatTopic(projectId,String(form.get('title')),String(form.get('description')));onOpen(topic.id);},'カードを作成');
 older.onclick=async()=>{if(loading||!messages.length)return;loading=true;older.disabled=true;try{const data=await chatMessages(current.id,messages[0]);await fetchProfiles(data.messages);if(!alive())return;messages=[...data.messages.filter(m=>!messages.some(old=>old.id===m.id)),...messages];more=data.more;drawMessages('prepend');}catch(error){notify(error.message);}finally{loading=false;older.disabled=false;}};
 composer.onsubmit=async event=>{event.preventDefault();const text=input.value.trim();if(!text||!current)return;const button=composer.querySelector('button');if(button.disabled)return;button.disabled=true;input.readOnly=true;root.querySelector('#chat-error').textContent='';if(text!==pendingText){pendingText=text;pendingId=id();}try{const message=await postChatMessage(current,text,pendingId);if(!alive())return;await append(message);input.value='';pendingId=null;pendingText=null;}catch(error){if(alive())root.querySelector('#chat-error').textContent=error.message;}finally{button.disabled=false;input.readOnly=false;if(alive())input.focus();}};
 input.onkeydown=event=>{if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();composer.requestSubmit();}};
 const refresh=document.createElement('button');refresh.type='button';refresh.textContent='最新の会話';refresh.className='chat-refresh';refresh.onclick=async()=>{try{await refreshTopics();if(current){const data=await chatMessages(current.id);for(const message of data.messages)await append(message);}}catch(error){notify(error.message)}};root.querySelector('.section-heading').append(refresh);
 initializeChat();return ()=>{disposed=true;if(channel)state.client.removeChannel(channel);};
}
