import {state,id} from './store.js';
import {studyStats} from './study-bank.js';
const previewKey='des-community-study-preview-v1';
function readRoomPreview(){try{return JSON.parse(localStorage.getItem(previewKey))||{topics:[],messages:[],attempts:[]};}catch{return {topics:[],messages:[],attempts:[]};}}
function writeRoomPreview(value){localStorage.setItem(previewKey,JSON.stringify(value));}
const rpcRow=result=>Array.isArray(result)?result[0]:result;
export async function chatTopics(projectId){if(state.preview)return readRoomPreview().topics.filter(t=>t.project_id===projectId).sort((a,b)=>b.created_at.localeCompare(a.created_at));const {data,error}=await state.client.from('school_chat_topics').select('*').eq('project_id',projectId).order('created_at',{ascending:false}).limit(100);if(error)throw error;return data;}
export async function chatMessages(topicId,cursor){if(state.preview){let rows=readRoomPreview().messages.filter(m=>m.topic_id===topicId);if(cursor)rows=rows.filter(m=>m.created_at<cursor.created_at||(m.created_at===cursor.created_at&&m.id<cursor.id));rows.sort((a,b)=>b.created_at.localeCompare(a.created_at)||b.id.localeCompare(a.id));return {messages:rows.slice(0,50).reverse(),more:rows.length>50};}let query=state.client.from('school_chat_messages').select('*').eq('topic_id',topicId).order('created_at',{ascending:false}).order('id',{ascending:false}).limit(51);if(cursor)query=query.or(`created_at.lt.${cursor.created_at},and(created_at.eq.${cursor.created_at},id.lt.${cursor.id})`);const {data,error}=await query;if(error)throw error;return {messages:data.slice(0,50).reverse(),more:data.length>50};}
export async function createChatTopic(projectId,title,description){if(state.preview){const local=readRoomPreview();const row={id:id(),project_id:projectId,title:title.trim(),description:description.trim(),created_by:state.user.id,created_at:new Date().toISOString()};local.topics.push(row);writeRoomPreview(local);return row;}const {data,error}=await state.client.rpc('create_school_chat_topic',{p_id:id(),p_project:projectId,p_title:title,p_description:description});if(error)throw error;return rpcRow(data);}
export async function postChatMessage(topic,content,messageId){if(state.preview){const local=readRoomPreview();const row={id:messageId,project_id:topic.project_id,topic_id:topic.id,author_id:state.user.id,content:content.trim(),created_at:new Date().toISOString()};if(!local.messages.some(m=>m.id===messageId))local.messages.push(row);writeRoomPreview(local);return row;}const {data,error}=await state.client.rpc('post_school_chat_message',{p_id:messageId,p_topic:topic.id,p_content:content});if(error){if(error.code==='23505'){const existing=await state.client.from('school_chat_messages').select('*').eq('id',messageId).single();if(!existing.error)return existing.data;}throw error;}return rpcRow(data);}
export async function chatProfiles(ids){if(state.preview)return [{id:state.user.id,...state.profile}];if(!ids.length)return [];const {data,error}=await state.client.from('profiles').select('id,name,avatar').in('id',[...new Set(ids)]);if(error)throw error;return data;}
export async function loadStudy(){if(state.preview){const attempts=readRoomPreview().attempts.filter(a=>a.user_id===state.user.id);return {summary:studyStats(attempts),history:attempts.slice().sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,100)};}const [stats,history]=await Promise.all([state.client.rpc('school_study_summary'),state.client.from('school_study_attempts').select('*').eq('user_id',state.user.id).order('created_at',{ascending:false}).limit(100)]);if(stats.error)throw stats.error;if(history.error)throw history.error;return {summary:stats.data,history:history.data};}
export async function saveStudyAttempt(attempt){const row={...attempt,user_id:state.user.id};if(state.preview){const local=readRoomPreview();if(!local.attempts.some(a=>a.id===row.id))local.attempts.push({...row,created_at:new Date().toISOString()});writeRoomPreview(local);return;}const {error}=await state.client.from('school_study_attempts').insert(row);if(error&&error.code!=='23505')throw error;}
