import { config } from './config.js';
export const id = () => crypto.randomUUID();
export const configured = !!(config.supabaseUrl && config.supabasePublishableKey);
const initial = () => ({projects:[{id:'demo-project',name:'校内ポータル開発',description:'2人でつくる、部署を超えた共同開発の場所。',department:'',visibility:'private',owner_id:'preview',repo:'',created_at:new Date().toISOString()}],entities:[],profile:null});
export const state={client:null,user:null,profile:null,projects:[],entities:[],preview:false,channel:null,directoryChannel:null,directory:[],peers:[],role:'viewer',listeners:[],error:''};
export const emit=(event='data',data)=>state.listeners.forEach(fn=>fn(event,data));
let local;
function localRead(){try{return JSON.parse(localStorage.getItem('des-preview-v1'))||initial()}catch{return initial()}}
function localSave(){localStorage.setItem('des-preview-v1',JSON.stringify(local));}
export async function initialize(){
 if(configured){const {createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm');state.client=createClient(config.supabaseUrl,config.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data,error}=await state.client.auth.getSession();if(error)throw error;state.user=data.session?.user||null;
 state.client.auth.onAuthStateChange((event,session)=>{const previousId=state.user?.id;state.user=session?.user||null;if(event==='SIGNED_OUT'){state.profile=null;state.projects=[];state.entities=[];emit('auth')}else if(event==='SIGNED_IN'&&(previousId!==state.user?.id||!state.profile))setTimeout(()=>load().then(()=>emit('auth')).catch(e=>{state.error=e.message;emit('auth')}),0)});
 if(state.user)await load();
 }else if(localStorage.getItem('des-preview-entered'))enterPreview();
}
export function enterPreview(){state.preview=true;local=localRead();state.user={id:'preview',email:''};state.profile=local.profile;state.projects=local.projects;state.entities=local.entities;state.role='owner';localStorage.setItem('des-preview-entered','1');emit('auth');}
export async function signIn(email,password,signup){const {error}=signup?await state.client.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}}):await state.client.auth.signInWithPassword({email,password});if(error)throw error;return signup?'登録メールを確認してください。確認済みの場合はログインできます。':''}
export async function signOut(){await leaveRoom();if(state.preview){localStorage.removeItem('des-preview-entered');state.user=null;state.profile=null;state.preview=false;state.projects=[];state.entities=[];emit('auth')}else{const {error}=await state.client.auth.signOut();if(error)throw error}}
export async function load(){if(state.preview)return;const results=await Promise.all([state.client.from('profiles').select('*').eq('id',state.user.id).maybeSingle(),state.client.from('projects').select('*').order('created_at'),state.client.from('school_users').select('user_id').eq('user_id',state.user.id).maybeSingle()]);for(const r of results)if(r.error)throw r.error;if(!results[2].data)throw Error('この学校への参加許可がありません。管理者に登録メールアドレスを伝えてください。');state.profile=results[0].data;state.projects=results[1].data||[];}
export async function saveProfile(profile){const p={...profile,id:state.user.id};if(state.preview){local.profile=p;localSave()}else{const {error}=await state.client.from('profiles').upsert(p);if(error)throw error}state.profile=p;emit('auth');}
export async function createProject(p){const project={...p,id:id(),owner_id:state.user.id,created_at:new Date().toISOString()};if(state.preview){local.projects.push(project);localSave()}else{const {error}=await state.client.rpc('create_school_project',{p_id:project.id,p_name:project.name,p_description:project.description,p_department:project.department,p_visibility:project.visibility,p_repo:project.repo});if(error)throw error}if(!state.preview)state.projects.push(project);emit();return project;}
export async function selectProject(projectId){await leaveRoom();if(state.preview){state.entities=local.entities.filter(e=>e.project_id===projectId);state.role='owner';return}const [entities,membership]=await Promise.all([state.client.from('entities').select('*').eq('project_id',projectId).eq('deleted',false),state.client.from('project_members').select('role').eq('project_id',projectId).eq('user_id',state.user.id).maybeSingle()]);if(entities.error)throw entities.error;if(membership.error)throw membership.error;state.entities=entities.data||[];state.role=membership.data?.role||'viewer';}
export const canEdit=()=>state.role==='owner'||state.role==='editor';
export const list=(kind,projectId)=>state.entities.filter(e=>(!kind||e.kind===kind)&&(!projectId||e.project_id===projectId)&&!e.deleted);
export async function put(projectId,kind,payload,existingId,expectedVersion){if(!canEdit())throw Error('閲覧権限です。編集するにはメンバーとして招待してもらってください。');const previous=existingId?state.entities.find(e=>e.id===existingId):null;const entity={id:existingId||id(),project_id:projectId,kind,payload,version:(previous?.version||0)+1,deleted:false};
 if(state.preview){const index=local.entities.findIndex(e=>e.id===entity.id);if(index>=0)local.entities[index]=entity;else local.entities.push(entity);localSave()}
 else{const {data,error}=await state.client.rpc('save_entity',{p_id:entity.id,p_project:projectId,p_kind:kind,p_payload:payload,p_expected:expectedVersion ?? previous?.version ?? 0,p_deleted:false});if(error){if(error.message.includes('CONFLICT')){await refreshEntities(projectId);throw Error('他の人が更新しました。最新の内容を確認して再度編集してください。')}throw error}const saved=Array.isArray(data)?data[0]:data;if(!saved?.id)throw Error('保存結果を確認できませんでした。再読み込みしてください。');Object.assign(entity,saved)}
 const i=state.entities.findIndex(e=>e.id===entity.id);if(i>=0)state.entities[i]=entity;else state.entities.push(entity);emit();return entity;}
export async function remove(entity){if(!canEdit())throw Error('編集権限が必要です');if(state.preview){local.entities=local.entities.filter(e=>e.id!==entity.id);localSave()}else{const {error}=await state.client.rpc('save_entity',{p_id:entity.id,p_project:entity.project_id,p_kind:entity.kind,p_payload:entity.payload,p_expected:entity.version,p_deleted:true});if(error)throw error}state.entities=state.entities.filter(e=>e.id!==entity.id);emit();}
async function refreshEntities(projectId){const {data,error}=await state.client.from('entities').select('*').eq('project_id',projectId).eq('deleted',false);if(error)throw error;state.entities=data;emit()}
export async function leaveRoom(){if(state.channel){await state.client.removeChannel(state.channel);state.channel=null}if(state.directoryChannel){await state.client.removeChannel(state.directoryChannel);state.directoryChannel=null}state.peers=[];state.directory=[];}
export async function joinRoom(projectId,room){if(state.preview)return;await leaveRoom();const directory=state.client.channel(`room:${projectId}:directory`,{config:{private:true,presence:{key:state.user.id}}});state.directoryChannel=directory;directory.on('presence',{event:'sync'},()=>{state.directory=Object.values(directory.presenceState()).flat();emit('directory')}).subscribe(async status=>{if(status==='SUBSCRIBED')await directory.track({userId:state.user.id,name:state.profile?.name||'参加者',avatar:state.profile?.avatar||0,room})});const channel=state.client.channel(`room:${projectId}:${room}`,{config:{private:true,presence:{key:state.user.id}}});state.channel=channel;
 channel.on('postgres_changes',{event:'*',schema:'public',table:'entities',filter:`project_id=eq.${projectId}`},({new:row})=>{if(!row?.id)return;const i=state.entities.findIndex(e=>e.id===row.id);if(i>=0&&state.entities[i].version>row.version)return;if(row.deleted)state.entities=state.entities.filter(e=>e.id!==row.id);else if(i>=0)state.entities[i]=row;else state.entities.push(row);emit()}).on('presence',{event:'sync'},()=>{state.peers=Object.values(channel.presenceState()).flat();emit('presence')}).on('broadcast',{event:'cursor'},({payload})=>emit('cursor',payload)).subscribe(async status=>{if(status==='SUBSCRIBED'){await channel.track({userId:state.user.id,name:state.profile?.name||'参加者',avatar:state.profile?.avatar||0,room});emit('connection','接続済み')}else if(['CHANNEL_ERROR','TIMED_OUT','CLOSED'].includes(status))emit('connection','同期接続を確認してください');});}
export function cursor(payload){if(state.channel)state.channel.send({type:'broadcast',event:'cursor',payload:{...payload,userId:state.user.id,name:state.profile?.name,avatar:state.profile?.avatar}})}
export async function inviteMember(projectId,email,role){if(state.preview)throw Error('招待は共同利用の接続後に使えます。');const {error}=await state.client.rpc('invite_project_member',{p_project:projectId,p_email:email,p_role:role});if(error)throw error;}
export async function updateProject(projectId,changes){const p=state.projects.find(p=>p.id===projectId);if(!p)throw Error('プロジェクトがありません');if(state.preview){Object.assign(p,changes);localSave()}else{const {error}=await state.client.from('projects').update(changes).eq('id',projectId).select('id').single();if(error)throw error;Object.assign(p,changes)}emit()}

export async function projectMembers(projectId){
 if(state.preview)return [{user_id:state.user.id,role:'owner',name:state.profile?.name||'自分',avatar:state.profile?.avatar||0}];
 const {data:members,error}=await state.client.from('project_members').select('user_id,role').eq('project_id',projectId);if(error)throw error;
 if(!members.length)return [];
 const {data:profiles,error:profileError}=await state.client.from('profiles').select('id,name,avatar').in('id',members.map(m=>m.user_id));if(profileError)throw profileError;
 return members.map(m=>({...m,...(profiles.find(p=>p.id===m.user_id)||{name:'プロフィール未設定',avatar:0})}));
}
export function projectBackup(projectId){const project=state.projects.find(p=>p.id===projectId);if(!project)throw Error('プロジェクトがありません');return {format:'digital-engineer-school',version:1,exportedAt:new Date().toISOString(),project:{name:project.name,description:project.description,visibility:project.visibility,repo:project.repo},entities:list(null,projectId)};}
export function validateBackup(value){if(value?.format!=='digital-engineer-school'||value.version!==1||!value.project||typeof value.project.name!=='string'||!Array.isArray(value.entities)||value.entities.length>5000)throw Error('学校のバックアップ形式を確認してください');if(new Set(value.entities.map(e=>e.id)).size!==value.entities.length)throw Error('バックアップ内のIDが重複しています');const kinds=['task','retro','resource','meeting','code','design','refine'];for(const e of value.entities){if(!kinds.includes(e.kind)||!e.payload||typeof e.payload!=='object'||Array.isArray(e.payload)||typeof e.id!=='string')throw Error('バックアップ内のデータ形式を確認してください')}return value;}
