import {state,id} from './store.js';
import {studyCategories,studyQuestions} from './study-bank.js';
import {loadStudy,saveStudyAttempt} from './community-data.js';
const studyEscape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let studyRuntime={user:null,course:'itpass',category:'strategy',run:null};
export function studyRoomHTML(){return `<section id="study-room" class="study-room"><div class="study-intro"><span>📖 自分のペースで学ぶ</span><h2>今日の一問が、明日の力になる。</h2><p>ITパスポート・TOEIC向けのオリジナル練習問題。解説を読んで、苦手分野を少しずつ復習しましょう。</p><small>公式過去問・模擬試験ではありません。TOEICは文法・語彙・読解のみで、スコア換算は行いません。</small></div><div id="study-content"><p class="muted">自分の学習履歴を読み込み中…</p></div></section>`;}
export function bindStudyRoom({notify}){
 const root=document.querySelector('#study-room');if(!root)return ()=>{};const content=root.querySelector('#study-content');let disposed=false,summary=null,history=[];
 if(studyRuntime.user!==state.user.id)studyRuntime={user:state.user.id,course:'itpass',category:'strategy',run:null};const session=studyRuntime;
 const alive=()=>!disposed&&root.isConnected&&state.user?.id===session.user;
 const categoryName=value=>studyCategories.find(c=>c[1]===value)?.[2]||value;
 const percent=(a,b)=>b?Math.round(a/b*100):0;
 const courseName=value=>value==='itpass'?'ITパスポート':'TOEIC';
 const timeLabel=value=>new Date(value).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
 const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});
 const questionById=value=>studyQuestions.find(q=>q.id===value);
 async function refresh(){const data=await loadStudy();if(!alive())return;summary=data.summary;history=data.history;draw();}
 function dashboard(){const totals=summary?.totals||{attempts:0,correct:0,seconds:0,completed:0},days=summary?.days||[];const todayAttempts=Number(days.find(d=>d.day===today())?.attempts||0);const week=Array.from({length:7},(_,i)=>{const date=new Date(Date.now()-(6-i)*86400000).toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});return {date,count:Number(days.find(d=>d.day===date)?.attempts||0)};});const max=Math.max(5,...week.map(d=>d.count));return `<div class="study-metrics"><div><small>解いた回数</small><strong>${totals.attempts}<em>回</em></strong></div><div><small>正答率</small><strong>${percent(totals.correct,totals.attempts)}<em>%</em></strong></div><div><small>正解済み問題</small><strong>${totals.completed}<em>/${studyQuestions.length}</em></strong></div><div><small>今日の目安 · 5問</small><strong>${todayAttempts}<em>/5</em></strong><progress value="${Math.min(5,todayAttempts)}" max="5"></progress></div></div><div class="study-layout"><section class="panel"><h3>7日間の学習記録</h3><div class="study-week">${week.map(d=>`<div><strong>${d.count}</strong><span style="height:${Math.max(4,d.count/max*80)}px" aria-label="${d.date} ${d.count}問"></span><small>${d.date.slice(5).replace('-','/')}</small></div>`).join('')}</div></section><section class="panel"><h3>自分だけの学習ノート</h3><p>履歴と進捗は本人のみ閲覧できます。繰り返し正解しても、正解済み問題数は重複して増えません。</p><small class="muted">取り組んだ時間：約${Math.round(Number(totals.seconds||0)/60)}分 · 進捗はこの練習問題集を基準にしています。</small></section></div>`;}
 function selector(){return `<nav class="tabs" aria-label="試験を選ぶ">${['itpass','toeic'].map(course=>`<button data-study-course="${course}" class="${session.course===course?'active':''}" aria-pressed="${session.course===course}">${courseName(course)}</button>`).join('')}</nav><div class="study-category-grid">${studyCategories.filter(c=>c[0]===session.course).map(([course,category,label])=>{const total=studyQuestions.filter(q=>q.category===category).length,stats=summary?.categories?.find(s=>s.category===category)||{attempts:0,correct:0,completed:0};return `<button class="study-category ${session.category===category?'selected':''}" data-study-category="${category}" aria-pressed="${session.category===category}"><strong>${label}</strong><span>正解済み ${stats.completed} / ${total}問</span><progress value="${stats.completed}" max="${total}"></progress><small>回答 ${stats.attempts}回 · 正答率 ${percent(stats.correct,stats.attempts)}%</small></button>`;}).join('')}</div><section class="panel study-start"><div><h3>${categoryName(session.category)}の問題に挑戦</h3><p class="muted">4択問題・正解と解説付き</p></div><label>問題数<select id="study-count"><option value="5">5問</option><option value="10">10問</option><option value="12">12問</option></select></label><label>出題方法<select id="study-mode"><option value="all">全問題からランダム</option><option value="weak">復習（直近100回の不正解）</option></select></label><button id="study-start" class="primary">勉強をはじめる →</button></section>`;}
 function historyHTML(){return `<details class="panel study-history"><summary>自分の学習履歴（直近100回）</summary><div class="study-history-list">${history.map(a=>{const q=questionById(a.question_id);return `<article><span class="tag ${a.correct?'study-correct':'study-wrong'}">${a.correct?'正解':'不正解'}</span><div><strong>${studyEscape(q?.prompt||a.question_id)}</strong><small>${courseName(a.course)} / ${categoryName(a.category)} · ${timeLabel(a.created_at)}</small><p>自分の回答：${studyEscape(q?.options[a.answer]||'－')}${q?' · 正解：'+studyEscape(q.options[q.answer]):''}</p>${q?'<details><summary>解説を読む</summary><p>'+studyEscape(q.explanation)+'</p></details>':''}</div></article>`;}).join('')||'<p class="muted">問題を解くと、ここに履歴が残ります。</p>'}</div></details>`;}
 function quizHTML(){const run=session.run;if(run.index>=run.questions.length)return `<section class="panel study-finish"><span>🌱 おつかれさまでした</span><h2>${run.results.filter(r=>r.correct).length} / ${run.questions.length}問 正解</h2><p>正解・解説は学習履歴から確認できます。</p><button id="study-finish" class="primary">分野と進捗に戻る</button></section>`;const q=run.questions[run.index],record=run.record;return `<section class="panel study-quiz"><div class="section-heading"><span>${courseName(q.course)} / ${categoryName(q.category)} · ${run.index+1} / ${run.questions.length}問</span><button id="study-stop">勉強を終える</button></div><progress value="${run.index}" max="${run.questions.length}"></progress>${q.passage?`<div class="study-passage" lang="en">${studyEscape(q.passage)}</div>`:''}<h2 ${q.course==='toeic'?'lang="en"':''}>${studyEscape(q.prompt)}</h2><form id="study-answer"><fieldset ${record?'disabled':''}><legend>答えを1つ選んでください</legend>${q.options.map((choice,i)=>`<label class="study-option ${record&&(i===q.answer)?'is-correct':''}"><input type="radio" name="answer" value="${i}" required ${record?.answer===i?'checked':''}><span>${String.fromCharCode(65+i)}.</span> ${studyEscape(choice)}</label>`).join('')}</fieldset>${record?`<div class="study-explanation" role="status"><strong>${record.correct?'正解です':'正解は '+String.fromCharCode(65+q.answer)+' です'}</strong><p>${studyEscape(q.explanation)}</p></div><p id="study-save-status" role="status">${record.saved?'履歴に保存しました。':record.error?'保存に失敗しました。再試行してください。':'履歴を保存しています…'}</p>${record.error?'<button type="button" id="study-retry">保存を再試行</button>':''}<button type="button" id="study-next" class="primary" ${record.saved?'':'disabled'}>${run.index+1===run.questions.length?'結果を見る':'次の問題 →'}</button>`:'<button class="primary">解答を確認</button>'}</form></section>`;}
 function draw(){if(!alive())return;content.innerHTML=dashboard()+(session.run?quizHTML():selector())+historyHTML();
 content.querySelectorAll('[data-study-course]').forEach(button=>button.onclick=()=>{session.course=button.dataset.studyCourse;session.category=session.course==='itpass'?'strategy':'grammar';draw();});content.querySelectorAll('[data-study-category]').forEach(button=>button.onclick=()=>{session.category=button.dataset.studyCategory;draw();});
 const start=content.querySelector('#study-start');if(start)start.onclick=()=>{let questions=studyQuestions.filter(q=>q.category===session.category);if(content.querySelector('#study-mode').value==='weak'){const latest=new Map();for(const record of history)if(!latest.has(record.question_id))latest.set(record.question_id,record);questions=questions.filter(q=>latest.has(q.id)&&!latest.get(q.id).correct);if(!questions.length){notify('この分野の最近の不正解はありません。全問題から挑戦できます。');return;}}for(let i=questions.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[questions[i],questions[j]]=[questions[j],questions[i]];}session.run={questions:questions.slice(0,Number(content.querySelector('#study-count').value)),index:0,started:Date.now(),results:[],record:null};draw();content.querySelector('.study-quiz')?.scrollIntoView({behavior:'smooth',block:'start'});};
 const form=content.querySelector('#study-answer');if(form)form.onsubmit=event=>{event.preventDefault();const run=session.run;if(run.record)return;const q=run.questions[run.index],answer=Number(new FormData(form).get('answer'));run.record={id:id(),question_id:q.id,course:q.course,category:q.category,answer,correct:answer===q.answer,elapsed_seconds:Math.min(3600,Math.max(0,Math.round((Date.now()-run.started)/1000))),saved:false,error:false};draw();persistAnswer();};
 const retry=content.querySelector('#study-retry');if(retry)retry.onclick=persistAnswer;
 const next=content.querySelector('#study-next');if(next)next.onclick=()=>{const run=session.run;if(!run.record?.saved)return;run.results.push(run.record);run.index++;run.record=null;run.started=Date.now();draw();};
 const stop=content.querySelector('#study-stop');if(stop)stop.onclick=()=>{if(session.run.record&&!session.run.record.saved){notify('解答の保存が完了してから終了してください。');return;}session.run=null;draw();};
 const finish=content.querySelector('#study-finish');if(finish)finish.onclick=()=>{session.run=null;draw();};
 }
 async function persistAnswer(){const record=session.run?.record;if(!record||record.saved||record.saving)return;record.saving=true;record.error=false;draw();try{const {saved,error,saving,...attempt}=record;await saveStudyAttempt(attempt);record.saved=true;}catch(error){record.error=true;record.saving=false;draw();if(alive())notify(error.message);return;}record.saving=false;draw();try{await refresh();}catch(error){if(alive())notify('解答は保存済みです。進捗の再読み込みに失敗しました。');} }
 refresh().catch(error=>{if(alive()){content.innerHTML=`<p role="alert">${studyEscape(error.message)}</p><button id="study-load-retry">再読み込み</button>`;content.querySelector('#study-load-retry').onclick=()=>refresh().catch(e=>notify(e.message));}});return ()=>{disposed=true;};
}
