import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema realtime;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;create function realtime.topic() returns text language sql stable as $$ select current_setting('realtime.topic',true) $$;create table realtime.messages(topic text,extension text);alter table realtime.messages enable row level security;grant usage on schema public,auth,realtime to authenticated;grant select,insert on realtime.messages to authenticated;`);
// PGlite has no logical replication. Exercise the migration's tables, policies,
// triggers and RPCs exactly; omit ONLY its publication setup block.
let sql=await readFile('supabase/schema.sql','utf8');sql=sql.replace(/do \$\$ begin\n if not exists\(select 1 from pg_publication_tables[\s\S]*?end \$\$;/,'');await db.exec(sql);await db.exec(await readFile('supabase/invitations.sql','utf8'));
const owner='00000000-0000-4000-8000-000000000001',editor='00000000-0000-4000-8000-000000000002',viewer='00000000-0000-4000-8000-000000000003',outsider='00000000-0000-4000-8000-000000000004';
await db.exec(`insert into public.school_allowed_emails values('owner@example.com'),('editor@example.com'),('viewer@example.com');insert into auth.users values('${owner}','owner@example.com',now()),('${editor}','editor@example.com',now()),('${viewer}','viewer@example.com',now()),('${outsider}','outsider@example.com',now());`);
async function asUser(uid){await db.exec('reset role');await db.exec(`select set_config('request.jwt.claim.sub','${uid}',false);set role authenticated;`)}
const privateId='00000000-0000-4000-8000-000000000010',publicId='00000000-0000-4000-8000-000000000011',entity='00000000-0000-4000-8000-000000000020';
await asUser(owner);await db.query('select create_school_project($1,$2,$3,$4,$5,$6)',[privateId,'Private','','DX','private','']);await db.query('select create_school_project($1,$2,$3,$4,$5,$6)',[publicId,'Public','','DX','public','']);await db.query('select save_entity($1,$2,$3,$4,$5,$6)',[entity,privateId,'task',{title:'A'},0,false]);
await db.query('update projects set name=$1,description=$2,visibility=$3 where id=$4 returning id',['変更後','目標','private',privateId]);await assert.rejects(db.query('update projects set owner_id=$1 where id=$2',[editor,privateId]),/permission denied/);await asUser(viewer);assert.equal((await db.query('select * from projects')).rows.length,1);assert.equal((await db.query('select * from entities')).rows.length,0);await assert.rejects(db.query('select save_entity($1,$2,$3,$4,$5,$6)',[entity,privateId,'task',{title:'attack'},1,false]),/FORBIDDEN/);await assert.rejects(db.query('select invite_project_member($1,$2,$3)',[privateId,'viewer@example.com','editor']),/FORBIDDEN/);
await asUser(outsider);assert.equal((await db.query('select * from projects')).rows.length,0);await assert.rejects(db.query('select create_school_project($1,$2,$3,$4,$5,$6)',['00000000-0000-4000-8000-000000000090','attack','','','public','']),/FORBIDDEN/);
await asUser(owner);await db.query('select invite_project_member($1,$2,$3)',[privateId,'editor@example.com','editor']);await db.query('select invite_project_member($1,$2,$3)',[privateId,'viewer@example.com','viewer']);
await asUser(editor);assert.equal((await db.query('select * from projects')).rows.length,2);assert.equal((await db.query('update projects set name=$1 where id=$2 returning id',['権限外',privateId])).rows.length,0);assert.equal((await db.query('select name from projects where id=$1',[privateId])).rows[0].name,'変更後');await db.query('select save_entity($1,$2,$3,$4,$5,$6)',[entity,privateId,'task',{title:'B'},1,false]);await assert.rejects(db.query('select save_entity($1,$2,$3,$4,$5,$6)',[entity,privateId,'task',{title:'stale'},1,false]),/CONFLICT/);await assert.rejects(db.query('update project_members set role=$1 where user_id=$2',['owner',editor]),/permission denied/);
await asUser(viewer);assert.equal((await db.query('select * from entities')).rows.length,1);await assert.rejects(db.query('select save_entity($1,$2,$3,$4,$5,$6)',[entity,privateId,'task',{title:'attack'},2,false]),/FORBIDDEN/);
await asUser(owner);await db.query('select save_entity($1,$2,$3,$4,$5,$6)',[entity,privateId,'task',{title:'B'},2,true]);assert.equal((await db.query('select * from entities where not deleted')).rows.length,0);assert.equal((await db.query('select can_join_school_topic($1) as allowed',[`room:${privateId}:design`])).rows[0].allowed,true);await asUser(outsider);assert.equal((await db.query('select can_join_school_topic($1) as allowed',[`room:${privateId}:design`])).rows[0].allowed,false);
// New recipients are admitted only after verified-email redemption.
const invite='00000000-0000-4000-8000-000000000060',newUser='00000000-0000-4000-8000-000000000061';
await asUser(viewer);await assert.rejects(db.query('select create_school_invitation($1,$2,$3,$4)',[invite,privateId,'new@example.com','editor']),/FORBIDDEN/);
await asUser(owner);await assert.rejects(db.query('select create_school_invitation($1,$2,$3,$4)',[invite,privateId,'new@example.com','owner']),/INVALID_REQUEST/);await db.query('select create_school_invitation($1,$2,$3,$4)',[invite,privateId,'NEW@example.com','editor']);await assert.rejects(db.query('insert into school_invitations(id,project_id,email,role,invited_by) values($1,$2,$3,$4,$5)',[newUser,privateId,'attack@example.com','editor',owner]),/permission denied/);
await db.exec('reset role');await db.query('insert into auth.users(id,email,email_confirmed_at) values($1,$2,null)',[newUser,'new@example.com']);await asUser(newUser);await assert.rejects(db.query('select accept_school_invitations()'),/メール確認/);assert.equal((await db.query('select * from projects')).rows.length,0);
await db.exec('reset role');await db.query('update auth.users set email_confirmed_at=now() where id=$1',[newUser]);await asUser(outsider);assert.equal((await db.query('select accept_school_invitations()')).rows[0].accept_school_invitations,0);assert.equal((await db.query('select * from school_invitations')).rows.length,0);
await asUser(newUser);assert.equal((await db.query('select accept_school_invitations()')).rows[0].accept_school_invitations,1);assert.equal((await db.query('select role from project_members where project_id=$1 and user_id=$2',[privateId,newUser])).rows[0].role,'editor');assert.equal((await db.query('select accept_school_invitations()')).rows[0].accept_school_invitations,0);await assert.rejects(db.query('select cancel_school_invitation($1)',[invite]),/FORBIDDEN/);
const cancelled='00000000-0000-4000-8000-000000000062';await asUser(owner);await db.query('select create_school_invitation($1,$2,$3,$4)',[cancelled,privateId,'cancelled@example.com','viewer']);await db.query('select cancel_school_invitation($1)',[cancelled]);await db.exec('reset role');await db.query('insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())',['00000000-0000-4000-8000-000000000063','cancelled@example.com']);assert.equal((await db.query('select * from school_users where user_id=$1',['00000000-0000-4000-8000-000000000063'])).rows.length,0);
console.log('PASS: project permissions, invitation owner checks, role validation, email confirmation, exact recipient matching, idempotent redemption, cancellation and RLS isolation.');await db.close();
